### ISSUE TITLE
[Update] : Add My Profile in Profile-a-Thon

### ISSUE THREAD

**Issue by Cibiyanna26** [CodeMacrocosm/profileathon-22#76]
I am a contributor from hacktoberfest and I would like to add my profile in profile-a-thon.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by shreyamalogi** [comment]
go ahead!! @Cibiyanna26 @lakshyeahh

**Comment by Cibiyanna26** [comment]
@shreyamalogi Sorry to trouble you, it would be great if you assign the issues and  HacktoberFest have mentioned to add hacktoberfest label on the issues.

**Comment by lakshyeahh** [comment]
#80 has been raised please merge it

**Comment by Cibiyanna26** [comment]
@shreyamalogi #81 raised the pr.
