### ISSUE TITLE
[Bug] : Undefined User Profile

### ISSUE THREAD

**Issue by Cibiyanna26** [CodeMacrocosm/profileathon-22#77]
**Bug**
      User profiles are not showing, they are showing as undefined.

what the pr will resolve:
    Will find what is the issue and will debug the issue. The undefined error will be handled and user profiles will be shown.

![image](https://github.com/user-attachments/assets/1a82a550-8e60-4429-b10f-03ad8415a17a)

**Comment by Cibiyanna26** [comment]
I am a contributor from hacktoberfest and I would like to work on this issue.

**Comment by shreyamalogi** [comment]
Thank you @Cibiyanna26 but the issue has already been resolved; please let me know if you’d like any details!
